export const theme = {
  colorBlack: "#000000",
  colorWhite: "#fff",
  colorGray: "gray",
  colorLightGray: "lightgray",
  colorDarkGray: "#212121",
  colorRed: "red",
  colorLightBlue: "lightblue",
  colorReact: "#58C4DC",
  colorDarkBlue: "#001E32",
  colorAccentOrange: "#b3752f",
  colorDarkYellow: "#e9dc2e",
  colorCake: "#fff3db",
  colorDarkCake: "#f2e0ba",
  colorDarkRed: "#4b0201",
  colorLime: "#e8f574",
  colorLightPurple: "#a99cf5",
  colorLightPink: "#edb6d0",
  colorLightBlack: "#1b1b1b",
};
